#! /bin/csh
if ( $#argv == 0 ) then
	echo "syntax: offsets directory limit_lo limit_hi fwhm accept"
	exit 1
endif
cp /dev/null /tmp/offsets.dat
cp /dev/null /tmp/offsets.log
cp /dev/null /tmp/offsets.txt
cd $1
foreach f (`ls`)
echo 'spectrum: ' $1/$f 
peakfind -spectrum $1/$f -limit $2 $3 -fwhm $4 -accept $5 | rmbrace | lsqs
end
order_offsets
cd $HOME
